### ISSUE TITLE
💡️[Enhancement]:[FileMonitor] Running status

### ISSUE THREAD

**Issue by goldfoxweb** [David-Maisonave/Axter-Stash#2]
### If feature request is related to a problem, give a clear and concise description of what is the problem. Ex. I'm always frustrated when [...]. Do NOT use Feature-Request for issues related to errors. Instead, please create a [Bug Report].

Ability to see the running status of the service

### Describe the solution you'd like. A clear and concise description of what you want to happen.

A view of the service status

**Comment by David-Maisonave** [comment]
> Ability to see the running status of the service

You can currently detect if it's running by enable debug tracing, and monitoring filemonitor.log file.
![FileMonitor_DebugTracingEnabled](https://github.com/user-attachments/assets/b5799ac7-256a-4c30-b3ac-328de81b24b7)

The FileMonitor log file is in the following path:
`Stash\plugins\FileMonitor\filemonitor.log`

In the log file you'll see the following line popup about every 60 seconds:
![FileMonitorLogging](https://github.com/user-attachments/assets/b25492ff-f263-43dc-9155-d1b387de452a)

When FileMonitor is running as a service, it's not logging to the Stash log file. I need to look into this more, to see if I can change that.  That'll make it easier for user to see from the Stash GUI when the service is running.

**Comment by goldfoxweb** [comment]
Thanks for the feedback, so this might be a bug/quirk then. 

I’m running the latest version of stash and the plug-in was installed via the gui, this is all running in a docker container.

I have already turned on debugging but file has not been created. 

The file path is different,
Stash\plugins\community\FileMonitor

Will uninstall when I get some time and do a manual install to the ‘root’ of the plugin directory.

**Comment by David-Maisonave** [comment]
> The file path is different

1. What is the file path relative to where Stash is installed?
  - When running FileMonitor, the **exec:** section of the **filemonitor.yml** file tells Stash how to start the plugin.
```
exec:
  - python
  - "{pluginDir}/filemonitor.py"
```
2. Is that properly setup for your path?
3. Are you running FileMonitor as a service by clicking on the button **[Start Library Monitor Service]**?
<img width="500" alt="FileMonitorService" src="https://github.com/user-attachments/assets/b12aeca9-37a8-447f-90da-26e9440735ad">


4. Have you also tried running it as a plugin by clicking the **[Monitor as a Plugin]**?
<img width="500" alt="FileMonitor_Stash_UI_Tasks-PluginTasks_Start_MonitorAsPlugin" src="https://github.com/user-attachments/assets/d2ccdf43-0881-4715-94d0-fb7512b4d954">

Before trying to start it as a plugin, first click on the **[Stop Library Monitor]** button, and then click the **[Monitor as a Plugin]**. 

When FileMonitor is running as a plugin, you'll see it listed under the Task Queue. When a file change occurs, it will add a scan job to the Task Queue, and it will also add itself (FileMonitor) to the Task Queue and then exit.

> this is all running in a docker container.

I'm really not that familiar with Docker. 
6. Does Docker simulate a particular OS, and if so, which OS is it running?

I tried setting a Stash image using instructions in this website: https://hub.docker.com/r/stashapp/stash
But I got the following error:
```
E:\Stash>docker pull stashapp/stash
Using default tag: latest
error during connect: Post "http://%2F%2F.%2Fpipe%2FdockerDesktopLinuxEngine/v1.46/images/create?fromImage=stashapp%2Fstash&tag=latest":
 open //./pipe/dockerDesktopLinuxEngine: The system cannot find the file specified.
```
Do you have any tips on setting up Stash with Docker?
How did you create your setup?

**Comment by David-Maisonave** [comment]
Version 1.0.0 now has a running status.
  - To check running status of FileMonitor, use the Settings->Tools->FileMonitor option.
  - ![Screenshot 2024-11-29 071301](https://github.com/user-attachments/assets/640c34f4-228d-4a85-aba8-69626c3ac850)
    - If FileMonitor is running, it'll display the following screen:
    - ![Screenshot 2024-11-29 071836](https://github.com/user-attachments/assets/28ac9de3-c41a-46cd-8cda-7751fb3e50bb)

You can get the 1.0.0 version from the following link [https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/FileMonitor](https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/FileMonitor) now.

It will get it uploaded some time next week to the [CommunityScripts/tree/main/plugins/FileMonitor](https://github.com/stashapp/CommunityScripts/tree/main/plugins/FileMonitor).
