### ISSUE TITLE
🛗[RFC]: How to install the python requirements in the Stash Docker container?

### ISSUE THREAD

**Issue by nothing2obvi** [David-Maisonave/Axter-Stash#6]
### Optional title of the topic to discuss.

How to install the python requirements in the Stash Docker container?

### Describe the scope of your topic and your goals ideally within a single paragraph or TL. A summary that makes it easier for people to determine if they can contribute at a glance.

I'm trying to use FileMonitor, but I can't install the python requirements in the Stash Docker container.

### Only required if summary and title doesn't cover everything.

1. `docker exec -it stash /bin/sh`
2. `cd ~/.stash/plugins/FileMonitor`
3. `pip install -r requirements.txt`
4. Get the following error:

```
error: externally-managed-environment

× This environment is externally managed
╰─> 
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
    
    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:
    
    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage
    
    To exit the virtual environment, run:
    
    deactivate
    
    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.
    
    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by hqod** [comment]
Having the same issue

**Comment by David-Maisonave** [comment]
I ran Stash Docker about 3 months ago, and I remember having to follow the instructions in the note in order to get it to work.
>> note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

Follow the instructions, and if you still have issues, I'll setup a new Stash Docker setup to see if I can reproduce the issue.

**Comment by nothing2obvi** [comment]
I'll try it out, thanks.

Btw, where are those instructions? I don't see them [here](https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/FileMonitor).

**Comment by hqod** [comment]
> I'll try it out, thanks.
> 
> Btw, where are those instructions? I don't see them [here](https://github.com/David-Maisonave/Axter-Stash/tree/main/plugins/FileMonitor).

I think @David-Maisonave means running this following command:
`pip install -r requirements.txt --break-system-packages`

But as the warning says, overriding this may break the Python installation or the OS, is there another better solution as I'm running it on my NAS which doesn't seem to be a good choice for using this solution.

**Comment by David-Maisonave** [comment]
>> I think @David-Maisonave means running this following command:
pip install -r requirements.txt --break-system-packages

That's correct.  That is what I'm referring to.

>> But as the warning says, overriding this may break the Python installation or the OS

I'm **not** a Docker expert, so please take the following with a grain of salt.
When you run a Stash Docker, you're running a snapshot. I expect that you'll get that warning any time you try to make OS level changes to the snapshot.
That warning is a very generic warning, and keep in mind when it refers to "OS distribution provider" it's **not** referring to the host OS.

If you're worried about breaking the package, you can always make a copy of the package before adding the changes.

**Comment by nothing2obvi** [comment]
Hello, I tried to follow your new instructions on running FileMonitor as a script while using Stash in Docker. However, I get this error:

```
Traceback (most recent call last):
  File "/Users/username/Docker/stash/root/.stash/plugins/FileMonitor/filemonitor.py", line 169, in <module>
    for docker in stash.pluginConfig['dockers']:
                  ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'dockers'
```

**Comment by David-Maisonave** [comment]
That error indicates that there's an old version of **filemonitor_config.py** being used.
The filemonitor_config.py file should have the following:
``` Python
    # Docker notification from host machine
    "dockers": [ # Example Stash Docker configurations. For more details see https://github.com/David-Maisonave/Axter-Stash/blob/main/plugins/FileMonitor#Multiple-Stash-Docker-Configuration
        # # A simple basic example with only one bind mount path.
        # {"GQL":"http://localhost:9995", "apiKey":"", "bindMounts":[{r"C:\Video":"/mnt/Video"}]},
        
        # # Example having 8 bind mount paths.
        # {"GQL":"http://localhost:9997", "apiKey":"", "bindMounts":[
                # {r"C:\Users\admin3\AppData\Local\Docker\wsl\ManyMnt\data":"/data"},
                # {r"C:\Users\admin3\Videos":"/external"},
                # {r"C:\Users\admin3\Pictures":"/external2"},
                # {r"C:\Users\admin3\Downloads":"/external3"},
                # {r"E:\Downloads":"/external4"},
                # {r"E:\Celeb":"/external5"},
                # {r"F:\Hentai":"/external6"},
                # {r"Z:\Temp":"/external7"},
            # ]
        # },
        
        # # Example using the apiKey for a password configured Stash installation.
        # {"GQL":"http://localhost:9994", "apiKey":"eyJhb3676zgdUzI1NiIsInR5cCI6IwfXVCJ9.ewJ1aWQiOiJheHRlweIsInN1YiI6IkFQSUtleSIsImlhdewrweczNDU0MDk3N30.4nZVLk3xikjJZfZ0JTPA_Fic8JvFx3DZe5U21Zasdag", "bindMounts":[
                # {r"C:\Users\admin3\AppData\Local\Docker\wsl\MyStashContainer\data":"/data"},
                # {r"C:\Vid":"/mnt/Vid"},
                # {r"C:\Users\admin3\Downloads":"/mnt/Downloads"},
            # ]
        # },
    ],
```

The content associated with the **dockers** field is for user who which to monitor multiple Stash Dockers, but even if you're only monitoring a single Stash Docker instance, the field still has to be in the configuration file, but it can be empty.
Example:
``` Python
    # Docker notification from host machine
    "dockers": [ ],
```
